### ISSUE TITLE
Only index the abstract

### ISSUE THREAD

**Issue by bobvanluijt** [semi-technologies/arXiv-demo-dataset#1]
I would suggest to only set [this](https://github.com/semi-technologies/arXiv-demo-dataset/blob/f03646e7456f6ae9260d1ecc32828348a9c7e72a/schema.json#L83) one to `true` and all others (including the `vectorizeProperyName` and `vectorizeClassName`) to `false` so that it will only index the abstract without clutter.

**Comment by laura-ham** [comment]
> I would suggest to only set [this](https://github.com/semi-technologies/arXiv-demo-dataset/blob/f03646e7456f6ae9260d1ecc32828348a9c7e72a/schema.json#L83) one to `true` and all others (including the `vectorizeProperyName` and `vectorizeClassName`) to `false` so that it will only index the abstract without clutter.

I did this first, but that makes all the data values 'unsearchable', as in, you cannot do a graphql `where` search on any other fields then. See https://github.com/semi-technologies/weaviate/issues/1031.

**Comment by bobvanluijt** [comment]
Gotcha
